version: '3'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app_net
  pub:
    links:
      - redis
    build:
      dockerfile: ./Dockerfile
      context: ./pub
    image: manoelsilva/pub
    container_name: pub
    ports:
      - "8083:8083"
    networks: 
      - app_net
    depends_on:
      - redis
  sub:
    links:
      - redis
    build:
      dockerfile: ./Dockerfile
      context: ./sub
    image: manoelsilva/sub
    container_name: sub
    ports:
      - "8084:8084"
    networks: 
      - app_net
    depends_on:
      - redis
networks:
  app_net:
    driver: bridge